name: Build and Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger den Workflow, wenn ein Push auf den "main"-Branch erfolgt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds (optional, but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Ersetze dies durch deine Region

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t myapp:latest .

      # Tag the Docker image with the ECR repository URL
      - name: Tag the Docker image
        run: |
          docker tag myapp:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/myapp:latest

      # Push the Docker image to Amazon ECR
      - name: Push the Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/myapp:latest

  deploy:
    needs: build  # Der Deploy-Job läuft nur, wenn der Build-Job erfolgreich war
    runs-on: ubuntu-latest

    steps:
      # Check AWS CLI configuration
      - name: Check AWS CLI configuration
        run: |
          aws sts get-caller-identity

      # Deploy the image to Amazon ECS
      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment --region ${{ secrets.AWS_REGION }}
